apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: troopers
  labels:
    app: troopers
spec:
  type: NodePort
  ports:
  - port: 5000
    name: troopers
    targetPort: 5000
    nodePort: 30100
  selector:
    app: troopers
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: troopers
  name: troopers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: troopers
    spec:
      containers:
      - name: troopers
        image: $K8S_REGISTRY/troopers/troopers:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
